-- Correctif : ajoute/met à jour UNIQUEMENT les récompenses de la saison s1 (skins compris),
-- sans toucher aux dates ni aux réglages de la saison déjà en place dans bp_seasons.
-- À coller dans le SQL Editor de Supabase. Rejouable.

alter table public.bp_rewards drop constraint if exists bp_rewards_type_check;
alter table public.bp_rewards add constraint bp_rewards_type_check check (type in
  ('weaponSkin', 'title', 'icon', 'card', 'handSkin', 'enemySkin', 'arenaVariant', 'currency'));

insert into public.bp_rewards (season_id, track, reward_id, level, type)
values
  ('s1', 'free', 'title:recrue', 1, 'title'),
  ('s1', 'free', 'skin:vandal:dune', 1, 'weaponSkin'),
  ('s1', 'free', 'card:recon', 2, 'card'),
  ('s1', 'free', 'skin:glock:olive', 3, 'weaponSkin'),
  ('s1', 'free', 'points:4', 4, 'currency'),
  ('s1', 'free', 'title:tireur_regulier', 5, 'title'),
  ('s1', 'free', 'skin:sniper:urban', 5, 'weaponSkin'),
  ('s1', 'free', 'points:6', 6, 'currency'),
  ('s1', 'free', 'card:flick', 7, 'card'),
  ('s1', 'free', 'skin:vandal:cobalt', 8, 'weaponSkin'),
  ('s1', 'free', 'points:9', 9, 'currency'),
  ('s1', 'free', 'title:precis', 10, 'title'),
  ('s1', 'free', 'skin:glock:ivory', 10, 'weaponSkin'),
  ('s1', 'free', 'hands:desert', 11, 'handSkin'),
  ('s1', 'free', 'card:tracer', 12, 'card'),
  ('s1', 'free', 'skin:sniper:forest', 12, 'weaponSkin'),
  ('s1', 'free', 'skin:vandal:tidal', 13, 'weaponSkin'),
  ('s1', 'free', 'points:14', 14, 'currency'),
  ('s1', 'free', 'title:reflexes_vifs', 15, 'title'),
  ('s1', 'free', 'skin:glock:sunset', 15, 'weaponSkin'),
  ('s1', 'free', 'points:16', 16, 'currency'),
  ('s1', 'free', 'card:overdrive', 17, 'card'),
  ('s1', 'free', 'skin:sniper:amethyst', 17, 'weaponSkin'),
  ('s1', 'free', 'skin:vandal:redline', 18, 'weaponSkin'),
  ('s1', 'free', 'points:19', 19, 'currency'),
  ('s1', 'free', 'title:regularite', 20, 'title'),
  ('s1', 'free', 'skin:glock:volt', 20, 'weaponSkin'),
  ('s1', 'free', 'points:21', 21, 'currency'),
  ('s1', 'free', 'card:glacier', 22, 'card'),
  ('s1', 'free', 'skin:sniper:cryo', 22, 'weaponSkin'),
  ('s1', 'free', 'points:23', 23, 'currency'),
  ('s1', 'free', 'hands:arctic', 24, 'handSkin'),
  ('s1', 'free', 'title:chasseur_de_tetes', 25, 'title'),
  ('s1', 'free', 'skin:glock:futuristic', 25, 'weaponSkin'),
  ('s1', 'free', 'points:26', 26, 'currency'),
  ('s1', 'free', 'skin:vandal:circuit', 27, 'weaponSkin'),
  ('s1', 'free', 'points:28', 28, 'currency'),
  ('s1', 'free', 'card:ember', 29, 'card'),
  ('s1', 'free', 'title:oeil_de_lynx', 30, 'title'),
  ('s1', 'free', 'skin:sniper:glacier', 31, 'weaponSkin'),
  ('s1', 'free', 'points:32', 32, 'currency'),
  ('s1', 'free', 'hands:neon', 33, 'handSkin'),
  ('s1', 'free', 'title:veteran_s1', 34, 'title'),
  ('s1', 'free', 'skin:glock:synthwave', 34, 'weaponSkin'),
  ('s1', 'free', 'skin:vandal:aurora', 35, 'weaponSkin'),
  ('s1', 'free', 'points:36', 36, 'currency'),
  ('s1', 'free', 'card:vortex', 37, 'card'),
  ('s1', 'free', 'points:38', 38, 'currency'),
  ('s1', 'free', 'points:39', 39, 'currency'),
  ('s1', 'free', 'title:as_de_la_visee', 40, 'title'),
  ('s1', 'free', 'hands:crimson', 41, 'handSkin'),
  ('s1', 'free', 'skin:sniper:orbital', 42, 'weaponSkin'),
  ('s1', 'free', 'points:43', 43, 'currency'),
  ('s1', 'free', 'title:maitre_du_flick', 44, 'title'),
  ('s1', 'free', 'card:eclipse', 45, 'card'),
  ('s1', 'free', 'points:46', 46, 'currency'),
  ('s1', 'free', 'points:47', 47, 'currency'),
  ('s1', 'free', 'title:legende_du_tracking', 48, 'title'),
  ('s1', 'free', 'hands:prestige', 49, 'handSkin'),
  ('s1', 'free', 'title:champion_s1', 50, 'title'),
  ('s1', 'free', 'skin:vandal:singularity', 50, 'weaponSkin'),
  ('s1', 'free', 'card:singularity', 50, 'card')
on conflict (season_id, track, reward_id) do update set
  level = excluded.level,
  type = excluded.type;
